src/Entity/Centre.php
<?php

namespace App\Entity;

use App\Repository\CentreRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CentreRepository::class)]
#[ORM\InheritanceType('JOINED')]
#[ORM\DescriminatorColumn(name: 'discr', type: 'string')]
#[ORM\DiscriminatorMap(['centre' => Centre::class,'centre_tri' => CentreTri::class,'dechetterie' => Dechetterie::class, 'depot_sauvage' => DepotSauvage::class, 'reseau_incendie' => ReseauIncendie::class])]
class Centre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    protected ?int $id = null;

    #[ORM\Column(length: 255)]
    protected ?string $adresse = null;

    #[ORM\Column(length: 100)]
    protected ?string $ville = null;

    #[ORM\Column]
    protected ?int $code_postal = null;

    #[ORM\Column(length: 80)]
    protected ?string $nom_centre = null;

    #[ORM\Column(length: 90)]
    protected ?string $groupe = null;

    /*
    Erreur:
    The DQL alias 'r' contains an entity of an inheritance hierarchy with an empty discriminator value. This means that the database contains inconsistent data with an empty discriminator value in a table row.
    */
    protected $disc = 'centre';

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(int $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getNomCentre(): ?string
    {
        return $this->nom_centre;
    }

    public function setNomCentre(string $nom_centre): static
    {
        $this->nom_centre = $nom_centre;

        return $this;
    }

    public function getGroupe(): ?string
    {
        return $this->groupe;
    }

    public function setGroupe(string $groupe): static
    {
        $this->groupe = $groupe;

        return $this;
    }
    public function __toString()
    {

        return $this->ville;
    }
}

src/Entity/CentreTri.php
<?php

namespace App\Entity;

use App\Repository\CentreTriRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CentreTriRepository::class)]
class CentreTri extends Centre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    protected ?int $id = null;

    #[ORM\Column(length: 255)]
    protected ?string $tri_lieu = null;

    #[ORM\Column]
    protected ?float $tri_heure_am_debut = null;

    #[ORM\Column]
    protected ?float $tri_heure_am_fin = null;

    #[ORM\Column]
    protected ?float $tri_heure_pm_debut = null;

    #[ORM\Column]
    protected ?float $tri_heure_pm_fin = null;

    /*
    Erreur:
    The DQL alias 'r' contains an entity of an inheritance hierarchy with an empty discriminator value. This means that the database contains inconsistent data with an empty discriminator value in a table row.
    */
    protected $discr = 'centre_tri';

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTriLieu(): ?string
    {
        return $this->tri_lieu;
    }

    public function setTriLieu(string $tri_lieu): static
    {
        $this->tri_lieu = $tri_lieu;

        return $this;
    }

    public function getTriHeureAmDebut(): ?float
    {
        return $this->tri_heure_am_debut;
    }

    public function setTriHeureAmDebut(float $tri_heure_am_debut): static
    {
        $this->tri_heure_am_debut = $tri_heure_am_debut;

        return $this;
    }

    public function getTriHeureAmFin(): ?float
    {
        return $this->tri_heure_am_fin;
    }

    public function setTriHeureAmFin(float $tri_heure_am_fin): static
    {
        $this->tri_heure_am_fin = $tri_heure_am_fin;

        return $this;
    }

    public function getTriHeurePmDebut(): ?float
    {
        return $this->tri_heure_pm_debut;
    }

    public function setTriHeurePmDebut(float $tri_heure_pm_debut): static
    {
        $this->tri_heure_pm_debut = $tri_heure_pm_debut;

        return $this;
    }

    public function getTriHeurePmFin(): ?float
    {
        return $this->tri_heure_pm_fin;
    }

    public function setTriHeurePmFin(float $tri_heure_pm_fin): static
    {
        $this->tri_heure_pm_fin = $tri_heure_pm_fin;

        return $this;
    }
    public function __toString()
    {

        return $this->tri_lieu;
    }
}

src/Form/CentreTriType.php
<?php

namespace App\Form;

use App\Entity\CentreTri;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CentreTriType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('adresse')
            ->add('ville')
            ->add('code_postal')
            ->add('nom_centre')
            ->add('groupe')
            ->add('tri_lieu')
            ->add('tri_heure_am_debut')
            ->add('tri_heure_am_fin')
            ->add('tri_heure_pm_debut')
            ->add('tri_heure_pm_fin')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CentreTri::class,
        ]);
    }
}

src/Controller/Admin/CentreTriController.php
<?php

namespace App\Controller\Admin;

use App\Entity\CentreTri;
use App\Form\CentreTriType;
use App\Repository\CentreTriRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/centre/tri')]
class CentreTriController extends AbstractController
{
    #[Route('/', name: 'app_centre_tri_index', methods: ['GET'])]
    public function index(CentreTriRepository $centreTriRepository): Response
    {
        return $this->render('centre_tri/index.html.twig', [
            'centre_tris' => $centreTriRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_centre_tri_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CentreTriRepository $centreTriRepository): Response
    {
        $centreTri = new CentreTri();
        $form = $this->createForm(CentreTriType::class, $centreTri);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $centreTriRepository->save($centreTri, true);

            return $this->redirectToRoute('app_centre_tri_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('centre_tri/new.html.twig', [
            'centre_tri' => $centreTri,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_centre_tri_show', methods: ['GET'])]
    public function show(CentreTri $centreTri): Response
    {
        return $this->render('centre_tri/show.html.twig', [
            'centre_tri' => $centreTri,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_centre_tri_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, CentreTri $centreTri, CentreTriRepository $centreTriRepository): Response
    {
        $form = $this->createForm(CentreTriType::class, $centreTri);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $centreTriRepository->save($centreTri, true);

            return $this->redirectToRoute('app_centre_tri_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('centre_tri/edit.html.twig', [
            'centre_tri' => $centreTri,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_centre_tri_delete', methods: ['POST'])]
    public function delete(Request $request, CentreTri $centreTri, CentreTriRepository $centreTriRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$centreTri->getId(), $request->request->get('_token'))) {
            $centreTriRepository->remove($centreTri, true);
        }

        return $this->redirectToRoute('app_centre_tri_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/CentreTriController.php
<?php

namespace App\Controller;

use App\Entity\CentreTri;
use App\Form\CentreTriType;
use App\Repository\CentreTriRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/centre/tri')]
class CentreTriController extends AbstractController
{
    #[Route('/', name: 'app_centre_tri_index', methods: ['GET'])]
    public function index(CentreTriRepository $centreTriRepository): Response
    {
        return $this->render('centre_tri/index.html.twig', [
            'centre_tris' => $centreTriRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_centre_tri_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CentreTriRepository $centreTriRepository): Response
    {
        $centreTri = new CentreTri();
        $form = $this->createForm(CentreTriType::class, $centreTri);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $centreTriRepository->save($centreTri, true);

            return $this->redirectToRoute('app_centre_tri_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('centre_tri/new.html.twig', [
            'centre_tri' => $centreTri,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_centre_tri_show', methods: ['GET'])]
    public function show(CentreTri $centreTri): Response
    {
        return $this->render('centre_tri/show.html.twig', [
            'centre_tri' => $centreTri,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_centre_tri_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, CentreTri $centreTri, CentreTriRepository $centreTriRepository): Response
    {
        $form = $this->createForm(CentreTriType::class, $centreTri);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $centreTriRepository->save($centreTri, true);

            return $this->redirectToRoute('app_centre_tri_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('centre_tri/edit.html.twig', [
            'centre_tri' => $centreTri,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_centre_tri_delete', methods: ['POST'])]
    public function delete(Request $request, CentreTri $centreTri, CentreTriRepository $centreTriRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$centreTri->getId(), $request->request->get('_token'))) {
            $centreTriRepository->remove($centreTri, true);
        }

        return $this->redirectToRoute('app_centre_tri_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/centre_tri/_delete_form.html.twig
<form method="post" action="{{ path('app_centre_tri_delete', {'id': centre_tri.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ centre_tri.id) }}">
    <button class="btn">Delete</button>
</form>

templates/centre_tri/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit CentreTri{% endblock %}

{% block body %}
    <h1>Edit CentreTri</h1>

    {{ include('centre_tri/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_centre_tri_index') }}">back to list</a>

    {{ include('centre_tri/_delete_form.html.twig') }}
{% endblock %}

templates/centre_tri/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CentreTri index{% endblock %}

{% block body %}
    <h1>CentreTri index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Adresse</th>
                <th>Ville</th>
                <th>Code_postal</th>
                <th>Nom_centre</th>
                <th>Groupe</th>
                <th>Tri_lieu</th>
                <th>Tri_heure_am_debut</th>
                <th>Tri_heure_am_fin</th>
                <th>Tri_heure_pm_debut</th>
                <th>Tri_heure_pm_fin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for centre_tri in centre_tris %}
            <tr>
                <td>{{ centre_tri.id }}</td>
                <td>{{ centre_tri.adresse }}</td>
                <td>{{ centre_tri.ville }}</td>
                <td>{{ centre_tri.codePostal }}</td>
                <td>{{ centre_tri.nomCentre }}</td>
                <td>{{ centre_tri.groupe }}</td>
                <td>{{ centre_tri.triLieu }}</td>
                <td>{{ centre_tri.triHeureAmDebut }}</td>
                <td>{{ centre_tri.triHeureAmFin }}</td>
                <td>{{ centre_tri.triHeurePmDebut }}</td>
                <td>{{ centre_tri.triHeurePmFin }}</td>
                <td>
                    <a href="{{ path('app_centre_tri_show', {'id': centre_tri.id}) }}">show</a>
                    <a href="{{ path('app_centre_tri_edit', {'id': centre_tri.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_centre_tri_new') }}">Create new</a><br>
    <a href="{{ path('app_admin_accueil') }}">Retour à l'accueil administrateur</a>

{% endblock %}

templates/centre_tri/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New CentreTri{% endblock %}

{% block body %}
    <h1>Create new CentreTri</h1>

    {{ include('centre_tri/_form.html.twig') }}

    <a href="{{ path('app_centre_tri_index') }}">back to list</a>
{% endblock %}

templates/centre_tri/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}CentreTri{% endblock %}

{% block body %}
    <h1>CentreTri</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ centre_tri.id }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ centre_tri.adresse }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ centre_tri.ville }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ centre_tri.codePostal }}</td>
            </tr>
            <tr>
                <th>Nom_centre</th>
                <td>{{ centre_tri.nomCentre }}</td>
            </tr>
            <tr>
                <th>Groupe</th>
                <td>{{ centre_tri.groupe }}</td>
            </tr>
            <tr>
                <th>Tri_lieu</th>
                <td>{{ centre_tri.triLieu }}</td>
            </tr>
            <tr>
                <th>Tri_heure_am_debut</th>
                <td>{{ centre_tri.triHeureAmDebut }}</td>
            </tr>
            <tr>
                <th>Tri_heure_am_fin</th>
                <td>{{ centre_tri.triHeureAmFin }}</td>
            </tr>
            <tr>
                <th>Tri_heure_pm_debut</th>
                <td>{{ centre_tri.triHeurePmDebut }}</td>
            </tr>
            <tr>
                <th>Tri_heure_pm_fin</th>
                <td>{{ centre_tri.triHeurePmFin }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_centre_tri_index') }}">back to list</a>

    <a href="{{ path('app_centre_tri_edit', {'id': centre_tri.id}) }}">edit</a>

    {{ include('centre_tri/_delete_form.html.twig') }}
{% endblock %}