src/Entity/StatutAgent.php
<?php

namespace App\Entity;

use App\Repository\StatutAgentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StatutAgentRepository::class)]
class StatutAgent
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Statut $statut = null;

    #[ORM\ManyToOne(inversedBy: 'statutAgents')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getStatut(): ?Statut
    {
        return $this->statut;
    }

    public function setStatut(?Statut $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
    public function __toString()
    {

        return $this->date_debut;
    }
}

src/Form/StatutAgentType.php
<?php

namespace App\Form;

use App\Entity\StatutAgent;
use App\Entity\User;
use App\Entity\Statut;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

class StatutAgentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_debut', DateTimeType::class)
            ->add('date_fin', DateTimeType::class)
            ->add('statut', EntityType::class, [
                'class' => Statut::class,       
                'choice_label' => 'etat'
            ])
            ->add('user', EntityType::class, [
                'class' => User::class,       
                'choice_label' => 'prenom'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => StatutAgent::class,
        ]);
    }
}

src/Controller/Admin/StatutAgentController.php
<?php

namespace App\Controller\Admin;

use App\Entity\StatutAgent;
use App\Form\StatutAgentType;
use App\Repository\StatutAgentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/statut/agent')]
class StatutAgentController extends AbstractController
{
    #[Route('/', name: 'app_statut_agent_index', methods: ['GET'])]
    public function index(StatutAgentRepository $statutAgentRepository): Response
    {
        return $this->render('statut_agent/index.html.twig', [
            'statut_agents' => $statutAgentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_statut_agent_new', methods: ['GET', 'POST'])]
    public function new(Request $request, StatutAgentRepository $statutAgentRepository): Response
    {
        $statutAgent = new StatutAgent();
        $form = $this->createForm(StatutAgentType::class, $statutAgent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $statutAgentRepository->save($statutAgent, true);

            return $this->redirectToRoute('app_statut_agent_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('statut_agent/new.html.twig', [
            'statut_agent' => $statutAgent,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_statut_agent_show', methods: ['GET'])]
    public function show(StatutAgent $statutAgent): Response
    {
        return $this->render('statut_agent/show.html.twig', [
            'statut_agent' => $statutAgent,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_statut_agent_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, StatutAgent $statutAgent, StatutAgentRepository $statutAgentRepository): Response
    {
        $form = $this->createForm(StatutAgentType::class, $statutAgent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $statutAgentRepository->save($statutAgent, true);

            return $this->redirectToRoute('app_statut_agent_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('statut_agent/edit.html.twig', [
            'statut_agent' => $statutAgent,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_statut_agent_delete', methods: ['POST'])]
    public function delete(Request $request, StatutAgent $statutAgent, StatutAgentRepository $statutAgentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$statutAgent->getId(), $request->request->get('_token'))) {
            $statutAgentRepository->remove($statutAgent, true);
        }

        return $this->redirectToRoute('app_statut_agent_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/StatutAgentController.php
<?php

namespace App\Controller;

use App\Entity\StatutAgent;
use App\Form\StatutAgentType;
use App\Repository\StatutAgentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/statut/agent')]
class StatutAgentController extends AbstractController
{
    #[Route('/', name: 'app_statut_agent_index', methods: ['GET'])]
    public function index(StatutAgentRepository $statutAgentRepository): Response
    {
        return $this->render('statut_agent/index.html.twig', [
            'statut_agents' => $statutAgentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_statut_agent_new', methods: ['GET', 'POST'])]
    public function new(Request $request, StatutAgentRepository $statutAgentRepository): Response
    {
        $statutAgent = new StatutAgent();
        $form = $this->createForm(StatutAgentType::class, $statutAgent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $statutAgentRepository->save($statutAgent, true);

            return $this->redirectToRoute('app_statut_agent_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('statut_agent/new.html.twig', [
            'statut_agent' => $statutAgent,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_statut_agent_show', methods: ['GET'])]
    public function show(StatutAgent $statutAgent): Response
    {
        return $this->render('statut_agent/show.html.twig', [
            'statut_agent' => $statutAgent,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_statut_agent_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, StatutAgent $statutAgent, StatutAgentRepository $statutAgentRepository): Response
    {
        $form = $this->createForm(StatutAgentType::class, $statutAgent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $statutAgentRepository->save($statutAgent, true);

            return $this->redirectToRoute('app_statut_agent_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('statut_agent/edit.html.twig', [
            'statut_agent' => $statutAgent,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_statut_agent_delete', methods: ['POST'])]
    public function delete(Request $request, StatutAgent $statutAgent, StatutAgentRepository $statutAgentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$statutAgent->getId(), $request->request->get('_token'))) {
            $statutAgentRepository->remove($statutAgent, true);
        }

        return $this->redirectToRoute('app_statut_agent_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/statut_agent/_delete_form.html.twig
<form method="post" action="{{ path('app_statut_agent_delete', {'id': statut_agent.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ statut_agent.id) }}">
    <button class="btn">Delete</button>
</form>

templates/statut_agent/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/statut_agent/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit StatutAgent{% endblock %}

{% block body %}
    <h1>Edit StatutAgent</h1>

    {{ include('statut_agent/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_statut_agent_index') }}">back to list</a>

    {{ include('statut_agent/_delete_form.html.twig') }}
{% endblock %}

templates/statut_agent/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}StatutAgent index{% endblock %}

{% block body %}
    <h1>StatutAgent index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Agent</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>Statut</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for statut_agent in statut_agents %}
            <tr>
                <td>{{ statut_agent.id }}</td>
                <td>{{ statut_agent.user }}</td>
                <td>{{ statut_agent.dateDebut ? statut_agent.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ statut_agent.dateFin ? statut_agent.dateFin|date('Y-m-d') : '' }}</td>
                <td>{{ statut_agent.statut }}</td>

                <td>
                    <a href="{{ path('app_statut_agent_show', {'id': statut_agent.id}) }}">show</a>
                    <a href="{{ path('app_statut_agent_edit', {'id': statut_agent.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_statut_agent_new') }}">Create new</a><br>
    <a href="{{ path('app_admin_accueil') }}">Retour à l'accueil administrateur</a>

{% endblock %}

templates/statut_agent/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New StatutAgent{% endblock %}

{% block body %}
    <h1>Create new StatutAgent</h1>

    {{ include('statut_agent/_form.html.twig') }}

    <a href="{{ path('app_statut_agent_index') }}">back to list</a>
{% endblock %}

templates/statut_agent/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}StatutAgent{% endblock %}

{% block body %}
    <h1>StatutAgent</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ statut_agent.id }}</td>
            </tr>
            <tr>
                <th>Agent</th>
                <td>{{ statut_agent.user }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ statut_agent.dateDebut ? statut_agent.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ statut_agent.dateFin ? statut_agent.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ statut_agent.statut }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_statut_agent_index') }}">back to list</a>

    <a href="{{ path('app_statut_agent_edit', {'id': statut_agent.id}) }}">edit</a>

    {{ include('statut_agent/_delete_form.html.twig') }}
{% endblock %}